apiVersion: v1
kind: Template
labels:
  template: wustl-openjdk18-web-basic-s2i
  xpaas: 1.4.12
message: A new java application has been created in your project.
metadata:
  name: wustl-openjdk18-web-basic-s2i
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The application's http port.
    labels:
      application: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APP_NAME}
- apiVersion: v1
  id: ${APP_NAME}-http
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
    labels:
      application: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    host: ${HOSTNAME_HTTP}
    tls:
      insecureEdgeTerminationPolicy: Allow
      termination: edge
    to:
      name: ${APP_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APP_NAME}
    name: ${APP_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:dev
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        forcePull: true
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.3
          namespace: ${IMAGE_STREAM_NAMESPACE}
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APP_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APP_NAME}
          deploymentConfig: ${APP_NAME}
        name: ${APP_NAME}
      spec:
        containers:
        - env:
          - name: JAVA_APP_JAR
            value: ${FAT_JAR_NAME}
          image: ${APP_NAME}
          imagePullPolicy: Always
          name: ${APP_NAME}
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
        terminationGracePeriodSeconds: 75
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:dev
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: jenkins_edit
    namespace: ${PROJECT_NAME}
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: ${SA_NAME}
    namespace: ${PROJECT_NAME}
  userNames:
  - system:serviceaccount:${CICD_PROJECT_NAME}:${SA_NAME}
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APP_NAME
  required: true
  value: wustl-app
- description: Name of a service account that can deploy to this project
  name: SA_NAME
  required: true
  value: jenkins
- name: PROJECT_NAME
  required: true
- name: CICD_PROJECT_NAME
  required: true
- description: Name of the compiled app FAT JAR
  displayName: Compiled FAT JAR name
  name: FAT_JAR_NAME
  value: demo_java_jersey-1.0-SNAPSHOT-jar-with-dependencies.jar
- description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
  displayName: Custom http Route Hostname
  name: HOSTNAME_HTTP
- description: Git source URI for application
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/kfrankli/java-demo
- description: Git branch/tag reference
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
  value: master
- description: Path within Git project to build; empty for root project directory.
  displayName: Context Directory
  name: CONTEXT_DIR
  value: java-app
- description: GitHub trigger secret
  displayName: Github Webhook Secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
  required: true
- description: Generic build trigger secret
  displayName: Generic Webhook Secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GENERIC_WEBHOOK_SECRET
  required: true
- description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  displayName: ImageStream Namespace
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift
